replicaCount: 1

image:
  repository: ektowett/apisim
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: "apisim"
fullnameOverride: "apisim"

serviceAccount:
  create: false

podSecurityContext: {}

securityContext: {}

persistence:
  enabled: false

hook:
  name: db-migrate
  image:
    repository: ektowett/apisim-migrate
    tag: latest
    pullPolicy: IfNotPresent
  commands:
    - command: /go/bin/goose -dir /migrations postgres "${DB_URL}" up
  ttlSecondsAfterFinished: 0
  backoffLimit: 2
  activeDeadlineSeconds: 100

containerPort: 4027
containerName: http

service:
  type: ClusterIP
  port: 4027

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: dev-apisim.kip0127.cloud.okteto.net
      paths:
        - "/"

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

env:
  PORT: "4027"
  ENV: dev
  DB_URL: postgres://dev_apisim:r9ezxknwdyLe2nQu4U0tWUWdY5Wj8Rl7@frankfurt-postgres.render.com/dev_apisim
  REDIS_URL: redis://:T8mRbhtyjfspceQeYZn6XFc53WZa9NvW@3.249.127.82:6379
